# Site settings
title: Baasdesign Jekyll Template
email: info@baasdesign.nl
description: Baasdesign Jekyll Template
# for live
baseurl: "/jekyll"
siteurl: "http://baasdesign.github.io/"

#for local
# baseurl: ""
# siteurl: "localhost:4000"

twitter_username: baasdesign
github_username:  baasdesign

# Build settings #
markdown: kramdown

prose:
  rooturl: '_posts'
  siteurl: 'http://baasdesign.github.io/jekyll/'
  relativeLinks: 'http://baasdesign.github.io/jekyll/links.jsonp'
  media: 'assets/images/'
  ignore:
    - _config.yml
    - /_layouts
    - /assets/js
    - /_includes
    - /_data
    - /_plugins
    - /_sass
    - /css
    - .gitignore
    - Gemfile
    - Gemfile.lock
  # metadata:
  #   _posts/blog:
  #   _posts/pages:
  #   _posts/projects:
