# Site settings
title: Laura Nagtegaal
email: laura.nagtegaal@hotmail.com
description: ...
# for live
baseurl: "/portfolio"
siteurl: "lauranagtegaal.github.io/portfolio"

#for local
# baseurl: ""
# siteurl: "localhost:4000"

twitter_username: Laura Nagtegaal
github_username:  Laura Nagtegaal

# Build settings #
markdown: kramdown
