# Site settings
title: Jekyll Mocksite
email: info@baasdesign.nl
description:
baseurl: "/jekyll"
siteurl: http://baasdesign.github.io/
twitter_username: baasdesign
github_username:  baasdesign

# Build settings
markdown: kramdown
