# Site settings
title: Baasdesign Jekyll Template
email: info@baasdesign.nl
description: Baasdesign Jekyll Template
# for live
baseurl: ""
siteurl: "http://chartreuse-goat1.cloudvent.net/"

#for local
# baseurl: ""
# siteurl: "localhost:4000"

twitter_username: baasdesign
github_username:  baasdesign

# Build settings #
markdown: kramdown
