# Site settings
title: iPublications Jekyll Template
email: info@ipublications.net
description: iPublications Jekyll Template
baseurl: "/jekyll" # the subpath of your site, e.g. /blog/
siteurl: "http://baasdesign.github.io/"
twitter_username: ipublications
github_username:  ipublications

# Build settings #
markdown: kramdown

prose:
  siteurl: 'http://prose.github.io/jekyll/'
  relativeLinks: 'http://prose.github.io/jekyll/links.jsonp'
  media: 'assets/images/'
  ignore:
    - _config.yml
    - /_layouts
    - /assets/js
    - /_includes
    - /_data
    - /_plugins
    - /_sass
    - /css
    - .gitignore
    - Gemfile
    - Gemfile.lock